# Generated by Django 4.2.17 on 2025-09-23 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=128)),
                ('target_object_id', models.CharField(max_length=64)),
                ('donor_object_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('dry_run', 'Dry run')], default='completed', max_length=32)),
                ('dry_run', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_manager_donor_operations', to='contenttypes.contenttype')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_operations', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_manager_target_operations', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='merge_manager_target_idx'), models.Index(fields=['donor_content_type', 'donor_object_id'], name='merge_manager_donor_idx'), models.Index(fields=['profile', 'created_at'], name='merge_manager_profile_idx')],
            },
        ),
    ]
